INSERT INTO apex_usuario_proyecto (proyecto, usuario_grupo_acc, usuario, usuario_perfil_datos) VALUES ('mocovi_dev', 'admin', 'agranados', NULL);
INSERT INTO apex_usuario_proyecto (proyecto, usuario_grupo_acc, usuario, usuario_perfil_datos) VALUES ('mocovi_dev', 'admin', 'compras', NULL);
INSERT INTO apex_usuario_proyecto (proyecto, usuario_grupo_acc, usuario, usuario_perfil_datos) VALUES ('mocovi_dev', 'presupesto', 'lgerez', NULL);
INSERT INTO apex_usuario_proyecto (proyecto, usuario_grupo_acc, usuario, usuario_perfil_datos) VALUES ('mocovi_dev', 'presupesto', 'nfernandez', NULL);
INSERT INTO apex_usuario_proyecto (proyecto, usuario_grupo_acc, usuario, usuario_perfil_datos) VALUES ('mocovi_dev', 'unidadacad', 'nfernandez', NULL);
INSERT INTO apex_usuario_proyecto (proyecto, usuario_grupo_acc, usuario, usuario_perfil_datos) VALUES ('mocovi_dev', 'excepcion', 'toba', NULL);
INSERT INTO apex_usuario_proyecto (proyecto, usuario_grupo_acc, usuario, usuario_perfil_datos) VALUES ('mocovi_dev', 'admin', 'toba', NULL);
INSERT INTO apex_usuario_proyecto (proyecto, usuario_grupo_acc, usuario, usuario_perfil_datos) VALUES ('mocovi_dev', 'presupesto', 'vparedes', NULL);
INSERT INTO apex_usuario_proyecto_perfil_datos (proyecto, usuario_perfil_datos, usuario) VALUES ('mocovi_dev', '819000003', 'lgerez');
INSERT INTO apex_usuario_proyecto_perfil_datos (proyecto, usuario_perfil_datos, usuario) VALUES ('mocovi_dev', '819000002', 'nfernandez');
